version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: trpg-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trpg-app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017
      MONGO_DATABASE: ${MONGO_DATABASE}
      BOT_TOKEN: ${BOT_TOKEN}

volumes:
  mongo-data: